name: Test soft

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for app
      run: |
        cd nextjs-blog
        npm install

    - name: Run tests
      run: |
        cd nextjs-blog
        npm run coverage